### ISSUE TITLE
[Forum] How and for what do you use MobileOrg (and org-mode)?

### ISSUE THREAD

**Issue by d12frosted** [MobileOrg/mobileorg#100]
Hey folks,

Since there is an [active conversation](https://paper.dropbox.com/doc/MobileOrg-ideas-dznQbK5Su2BNAXZl48iPG?t=497650550027528#:t=497650550027528) on the future of MobileOrg it would be really helpful to know how you use MobileOrg and what tasks you solve by using it. Also it would be great to know what features you miss. Note that there are [some open issues](https://github.com/MobileOrg/mobileorg/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) which you can vote for 😸 

Thanks in advance. 

P. S. Spreading this topic further would be helpful 😸

**Comment by jamie-conlon** [comment]
I use org-mode for GTD:
This mainly consists of:
- Agendas - Todo etc...
- Capturing to inbox
   - On iOS, capturing from outside the app would be great too. E.g. A homescreen widget and a share sheet option.
- Refilling
- Reference notes

**Comment by webframp** [comment]
org-mode is primary GTD tool as well, and I use MobileOrg for capture and visibility of agendas and references.

**Comment by d12frosted** [comment]
In short - GTD, time tracking and note taking. 

---

I was using `org-mode` for GTD (mostly for work related 'stuff'), time tracking and note taking. Everything was fine until I started to overcomplicate things with calendar synchronisation (it never really worked well, because I have several calendars I have to follow) and macOS (formerly OS X) notifications. Notifications worked well but thanks to semi-working calendar synchronisation I have disabled Calendar.app notifications and after I missed several important notifications about updated events I just said myself that I have to do something with this, because my org-mode became unreliable. So I've started to use OmniFocus for GTD. It's really nice piece of software that really works. It's mobile application is just cool. Seriously. But on other hand it doesn't have time tracking, it forces to use mouse in some cases, I could not find a way to bind my custom scripts to a key sequence or combination. Also it allows you to create custom 'agendas', but they are not that flexible as agendas in `org-mode`. And the last thing - OmniFocus is not Emacs when it comes to text editing. Which is sad.

That being said I am confused, because OmniFocus is great and reliable as GTD system, but it lacks some things that are possible or available in `org-mode` and Emacs. So most possibly, I am going to return back to `org-mode` 😸 The thing that I would miss the most is the mobile version of OmniFocus. It's near perfect. And that's why I am so damn interested in a new version of MobileOrg 😸 

P. S. Sorry for the long comment.

**Comment by mgmart** [comment]
### Current Usage

I started to use org-mode several times and stopped using it because of the lack of mobile support. 
Main things I miss on the mobile site are notifications for todos and a proper note taking facility.
I'm a (pro) user of Evernote and Remember the Milk from their beginning and this is because of their fantastic mobile support.
I tried to utilise the rtm-link which is provided in org-mode contrib and geeknote to integrate both tools with org-mode but was not happy with the results. 

Now I'm again using org-mode for a while and feel the pain of the lacking mobile support. For the moment I'm using MobileOrg as a read only copy of my journal. I also carry my emacs.org file with me which is useful sometimes ;)

### Things I do with org-mode for which I wish support on mobile 
* ox-letter: so I could keep all my non electronic correspondence with me
* Clocking: to be able to use org's clocking feature while not at the computer
* I'm about to transfer my endurance training plan to org-mode. Currently it's in Curio - beside of calendar integration there is no mobile support either. 

###  Apps which I want to substitute with MobileOrg

* Evernote
	* Location based notes and map view 
	* Voice recordings
	* Photos with caption 
	* With rtm-link support of todos
		* Link to any document type link webpage, mail message etc

* Remember the Milk
	* Reminders (time based)
	* Todo Lists

* Photos
	* Photos and Map view

**Comment by mgmart** [comment]
is anybody active in the org-mode community? Probably it could be an approach to forward the question to the org-mode community as well.

**Comment by tuxella** [comment]
I could forward this survey to the org-mode newsgroup, this would reach some *advanced* users of org-mode.

I can also send it to a french emacs user-group, less than half of them know of org-mode but this would be a more diverse sample of users.

**Comment by Manzalab** [comment]
Is the survey about using MobileOrg or Org-mode in general?

If this is about MobileOrg, this thread is a good place to collect feedback, and you're welcome to advertize it on the org-mode mailing list.

If this is about org-mode in general... well, there is a lot of feedback already, asking for more will not provide a lot of value.  But if someone wants to design a proper survey, the community can sure help designing it, spreading it and replying to it.

**Comment by bzg** [comment]
Is the survey about using MobileOrg or Org-mode in general?

If this is about MobileOrg, this thread is a good place to collect feedback, and you're more than welcome to advertize it on the org-mode mailing list.

If this is about org-mode in general... well, there is a lot of feedback already, asking for more will not provide a lot of value I guess.

But if someone wants to design a proper org-mode survey, the community can sure help designing it, spreading it and replying to it.

**Comment by mgmart** [comment]
@bzg The survey is definitely about MobileOrg. We are asking about org-mode in this context because of use-cases we could cover in a future version of MobileOrg which are not possible at the moment with MobileOrg. I could imagine there are many Org-mode users out there who are not actively in development and GitHub. It would be shame if we complete the design of a new version of MobileOrg, only to realise that we have missed the need of the users.

@tuxella Are the newsgroup and the mailing-list identical? I think the more different the users are the better it is 😄. If you could be so kind to place the advertisement to this survey it would be appreciated very much.

I was asking about active users in the communities because I do not want to pop-up somewhere, place the advertisement to the survey only to vanish afterwords. I could imagine that in some communities there are also members without GitHub account. In this case the 'active user' could act as a proxy to this survey 😄

**Comment by bzg** [comment]
Thanks for the clarification.  In any case, I recommend a proper survey outside of github, not all org-mode users are on github.

**Comment by abradd** [comment]
You could post this question the org-mode subreddit.  One of the [Pandoc developers](https://www.reddit.com/r/orgmode/comments/4ilhln/do_you_use_pandoc_what_would_be_your_wishes/) did that recently and had some good feedback.

**Comment by mgmart** [comment]
@abradd thanks for the hint. Didn't know about the subreddit. There seems to be already much content relating to our question(s). I even found an Android App which is using git for sync instead of org-mobile.el. A feature we are also are thinking about.

**Comment by ckruse** [comment]
That would be awesome! I already have my org-files in a git repository, with an automatic commit every hour and finally I could change all my org-files on my phone!

**Comment by mgmart** [comment]
@ckruse any input on #120 would be appreciated 😄

**Comment by vermiculus** [comment]
At request: I haven't used the application in some time (ever since it was taken off the app store a few years ago), but I used it almost exclusively for task capture. Sometimes I used it to review old notes, but not often.

**Comment by wilbowma** [comment]
When I discovered MobileOrg, I was hoping to replace the Reminders and Notes apps with one app that also syncs well with a terminal based tools. MobileOrg is only just good enough for me.

I use org-mode primarily for 
1. capturing notes/tasks. This works very well, especially since it semi-automatically syncs with emacs.
2. reviewing/marking tasks from agenda. This works.. okay. Sometimes marking things done doesn't work right (filed in earlier bugs and may be addressed now), and I wish there was support for notifications.

I sometimes use it to refer to notes, but this doesn't work well on MobileOrg:
- requires far too many clicks to get to notes. (MobileOrg -> OrgFile -> Heading > ... Maybe SubHeadings ... -> View As Document)
- MobileOrg doesn't sync directory structures, under which most of my notes are organized.

**Comment by sjLambda** [comment]
Agenda, TODO, Reminders, Notes w/links, Capture are my current usage needs.

Clocking, QR capture, image capture from camera, and Bibliographic capture would be icing on the cake.

Thanks for your great app.

**Comment by brhumphe** [comment]
I think that, more than anything else, org-mode needs to integrate into my entire computing environment. On iOS that means robust support for x-callback urls, share-sheet extensions, notifications, and actions in third party apps like Drafts.

**Comment by webframp** [comment]
@brhumphe I'm also a Drafts user, what integration with MobileOrg would you like to see? How do you see it working best?

**Comment by brhumphe** [comment]
I see it working best as a bridge between other iOS apps and org files. For example, if I had an org file for task management, I could create an action in Drafts to add the contents of the draft underneath an Inbox header with a particular set of tags. Or if triggering from the share sheet, then a menu might open asking where to file the item, similar to OneNote. Perhaps it could automatically import and export markdown and taskpaper files. Heck, you could probably implement an entire CRUD API for org files through URL callbacks.

**Comment by alf** [comment]
- Capture of TODOs
- Capture of notes (requires structural editing)
- Browsing of agenda/org files
- Refiling would be nice (while commuting)
- Notification/Integration with reminders

**Comment by gvol** [comment]
Almost exclusively for capture (though that may change here soon).  I was going to try to create a Siri intent to capture something in MobileOrg, but when I looked at SiriKit I realized it isn't up to the task.  It's sad really.

**Comment by Biotechjones** [comment]
* Capture TODOs

**Comment by feoh** [comment]
I never got MobileOrg to work, but very much wanted it to :) Key features for me are clocking and simple outlining with links.

**Comment by robertsck** [comment]
I use org mode as a personal knowledge base, with a lot of links between files and headlines. I use ID links to allow me to change/move headings later. I currently use many small org files primarily to enable mobile support. Thus, a good mobile-org app would allow me to generate larger org files. 

Key features I would use are:
- Search across multiple org files
- autocompletion of tags and links to Headers using an ID link
- quick capture of notes
- since I store everything on dropbox, support of file links would be a great nice to have

**Comment by paulelms** [comment]
- capture + refile
- something similar to GTD
- agenda
- babel
- personal wiki and journal
- attachments
- encryption

**Comment by paulelms** [comment]
BTW, awesome tutorial on org-mode: http://doc.norang.ca/org-mode.html

**Comment by webframp** [comment]
> I never got MobileOrg to work, but very much wanted it to :) Key features for me are clocking and simple outlining with links.

@feoh we're also trying to improve the doc site: https://mobileorg.github.io/  if you could create [an issue on the repo for that site](https://github.com/MobileOrg/mobileorg.github.io/issues) describing what troubles you had we'll try and update things to make it easier to get setup. That's important for the current version as well as the planned v2

**Comment by jonmoore** [comment]
- todos
- organizing reading list and notes

Features I'd like: integration with the iOS "Send to" system, in particular I'd like to be able to send URLs from Safari to MobileOrg, and to send items from MobileOrg as email.

**Comment by ashmanskas** [comment]
There is a commercial (but user-extensible) iOS program called Editorial that does nice outline folding, but it works with Markdown rather than orgmode.  Many people have wished that Editorial could edit (or at least view) orgmode.  Perhaps some parts of Editorial's UI could serve as inspiration for the new mobileorg?

https://forum.omz-software.com/topic/2023/feature-org-mode-support

http://omz-software.com/editorial/

**Comment by k0105** [comment]
Time tracking. Last time I tried no mobile app did it right. If you fix the clock in and out functionality I'm perfectly happy. For me it never worked, time wasn't persisted etc. I just want to press clock in, have it record the first time stamp, hit stop, have a second time stamp added and this entry appended to the task entry, so I can synchronize it across environments. For me that's the one killer feature. Orgzly doesn't have it, the time tracking apps don't have decent todo lists - if you offer it you instantly become my #1 app.

**Comment by mgmart** [comment]
Last feedback was given a year back => closing to keep issue list clean
