### ISSUE TITLE
iPhone 5 incompatibility?

### ISSUE THREAD

**Issue by wilbowma** [MobileOrg/mobileorg#200]
I just tried to update MobileOrg hoping the WebDAV syncing issue would be fixed, but the AppStore reports that the new version is incompatible with my device. I'm running iOS 10.3.2 on an iPhone 5 (not 5s). The earlier version installed fine for the iPhone 5; is there some new incompatibility or was this a mistake in listing the compatible devices?

**Comment by webframp** [comment]
Sorry for that inconvenience! Nothing has specifically changed in that regard that I am aware of and it definitely wasn't intentional. The only device requirement is iOS 9, from iTunes Connect:

Device Requirements

Minimum iOS Version
9.0

Supported Architectures
arm64

Device Protocols
Device Family
iPhone / iPod touch, iPad

Required Capabilities
arm64

**Comment by wilbowma** [comment]
I think the arm64 requirement is causing the issue. IIRC, the iPhone 5 was still 32bit.

**Comment by ckruse** [comment]
You dropped arm32, didn't you?

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
Hu... sorry, @wilbowma was faster, I didn't want to hit send

**Comment by webframp** [comment]
It does look that way based on the [compatibility matrix](https://developer.apple.com/library/content/documentation/DeviceInformation/Reference/iOSDeviceCompatibility/DeviceCompatibilityMatrix/DeviceCompatibilityMatrix.html#//apple_ref/doc/uid/TP40013599-CH17-SW13). 

If anything this was done by XCode and not intentional. I don't recall any earlier commits that required us to remove 32 bit. I will look at getting it back and do a point release if needed to get it supported again.

**Comment by wilbowma** [comment]
Thanks a lot!

**Comment by webframp** [comment]
I've built a new bundle making sure to use the `Build Only Device` and confirmed build settings:

Build Active Architectures is `Yes`
Implicit 32bit is `Yes`
Valid Archs is `arm64 armv7 armv7s`

Before I submit to the store with a version bump anyone have suggestions to confirm that this bundle has 32bit and 64bit support?

**Comment by mgmart** [comment]
This matrix should provide all information needed:
![](https://i.stack.imgur.com/F5s5W.png)
https://stackoverflow.com/a/21422550

**Comment by webframp** [comment]
Rebuilt and submitted 1.7.4 for review

**Comment by webframp** [comment]
v1.7.4 passed review and should be available soon if not already. Please let me know your results, thanks.

**Comment by wilbowma** [comment]
This one installed okay and the WebDAV syncing issues seems to be fixed. It looks like this can be closed. 

FYI, when I first tried to update to 1.7.4, I got the same error, despite seeing the new version and all iPhones being listed in the compatibility section. However, being an experienced computer-er, I tried restarting the App Store and then it installed fine.

**Comment by webframp** [comment]
Excellent, thanks for confirming and sorry for the hassle.
