### ISSUE TITLE
Feature request: iCloud drive support

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#201]
From Kirill Simagin in the App Store Reviews.

Not sure if it's worth effort in the v1.7 series or if it's better to focus in v2

**Comment by mgmart** [comment]
As v2 does not get any feedback it seems best to file it into 1.7 for the time being.

**Comment by mgmart** [comment]
Tried to switch iCloud support on. Was not able to do it because Xcode was complaining that my Developer ID is not able to do that on MobileOrg. 

<img width="328" alt="mobileorg_xcodeproj" src="https://user-images.githubusercontent.com/3919652/29246976-4717e522-8008-11e7-9107-bafc52f0e42c.png">

It seems that only @webframp might be able to do that. Don't know if that would allow others to use that feature during development.

**Comment by webframp** [comment]
I'll take a look at this one

**Comment by webframp** [comment]
Will look at it, still setting up the new machine for dev work but almost done

**Comment by ra1nb0w** [comment]
some update?

**Comment by dive** [comment]
@webframp, hello. How is it going with iCloud support?

It would be nice to be able to check org-mode stuff on iPhone. And I do not like Beorg personally (ideologically and because it is a blackbox app). 

I can implement the feature by myself, but maybe you already started and can share the draft implementation.

**Comment by webframp** [comment]
Hey @dive I'd greatly appreciate any contributions. I've been far too busy with other demands and just unable to spend the time I want on this feature.

**Comment by dive** [comment]
@webframp, you can assign this task to me if you want. I have a prototype that works, but it will take some time to adapt the current synchronisation logic, implement missing parts and prepare an instruction on how to incorporate these changes.

**Comment by webframp** [comment]
Thanks @dive I'll work on the Testflight process. Let me know how it goes.
