### ISSUE TITLE
Not able to sync

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg#29]
Reported by @rahuljha and @Agagarin:

Not able to sync, I keep getting:
## 

Error downloading checksums

An error was encountered while downloading checksums.dat from the server. This file isn't required, but the error received was unusual. The error was:

Unexpected error

**Comment by applemcg** [comment]
This discussion needs to be linked onto the Mobile.Org appendix B:
http://orgmode.org/manual/MobileOrg.html#MobileOrg

If webframp's step-by-step "how to" is anywhere else, i surely missed it.   

Now, that said, a question:  since this thread is 2+ years since the last prior post, can I assume noone else has needed this since then?

**Comment by songxin1990** [comment]
shit
